insert into CURRENCY_EXCHANGE(id, CURRENCY_FROM , CURRENCY_TO , CONVERSION_MULTIPLE ,ENVIRONMENT ) values(10001, 'USD', 'INR', 65,'');
insert into CURRENCY_EXCHANGE(id, CURRENCY_FROM , CURRENCY_TO , CONVERSION_MULTIPLE ,ENVIRONMENT ) values(10002, 'EUR', 'INR', 52,'');
insert into CURRENCY_EXCHANGE(id, CURRENCY_FROM , CURRENCY_TO , CONVERSION_MULTIPLE ,ENVIRONMENT ) values(10003, 'AUD', 'INR', 35,'');
insert into CURRENCY_EXCHANGE(id, CURRENCY_FROM , CURRENCY_TO , CONVERSION_MULTIPLE ,ENVIRONMENT ) values(10004, 'UKD', 'INR', 54,'');